### ISSUE TITLE
File upload stuck in "Completing..."

### ISSUE THREAD

**Issue by ricnava00** [meganz/MEGAsync#1022]
I know the title is a duplicate of https://github.com/meganz/MEGAsync/issues/464, but since there have been no updates on that issue since 2023 when a patch was released, I assume that the old problem was fixed and this is a different one

I'm using 5.6.1 on Windows

It seems that all uploads of modified files just get stuck in "Completing..."
Restarting the application doesn't solve the problem

Uploading new files, or moving and deleting existing files all work
Moving the stuck file outside of synced folders, restarting the app and moving the file back fixes the issue but it's obviously not sustainable

**Comment by 6d657263757279** [comment]
Your solution "Moving the stuck file outside of synced folders, restarting the app and moving the file back" does not work in my case and I am having the same problem. For me, all files get stuck in "Completing..." and no amount of pausing, reinstalling, moving files, etc, actually does anything to remedy this. No other files can queue and even attempt to work because the max amount of transfers get stuck and nothing can proceed. I hope they fix this soon.

**Comment by 6d657263757279** [comment]
@ricnava00 I encourage you to try downloading an older version of MEGASync using the following link referenced in #1019 (https://megasync.en.uptodown.com/windows/versions) or using another source of your choosing. v4.12.1 seems to have solved this for me for now. Ensure you untick the "Update automatically" option in the app settings after reinstalling.

**Comment by ortmann** [comment]
Please write to bug@mega.nz with the subject line 1022, indicating your account's registered email address. Please accept our apologies for this issue. You may be able to help us fix it. Thank you!

**Comment by 6d657263757279** [comment]
@ortmann I have done so.

**Comment by xWTF** [comment]
Same issue here, seems to be related to file conflict. Files without conflict can be uploaded normally.
Both auto-resolved and manually resolved conflicts will result in the file stuck at `Completing` status.

The mitigation (`Moving the stuck file outside of synced folders, restarting the app and moving the file back`) won't work if you already have a bunch of conflict files and the upload queue is full of stuck files.

In this case, pause the sync and restart the app, delete (or move them away) all conflict local files and resume the sync, wait for the sync to complete, the app should re-download these files to local. Then, overwrite these local files with your new version should fix it. This is extremely tedious though, if you have thousands of files stuck at this state.

![image](https://github.com/user-attachments/assets/aad6aba7-9a15-4566-b739-f6b745ddfb3e)

![image](https://github.com/user-attachments/assets/48696979-b851-4403-bf87-eef01bb8ff4e)

**Comment by tomsimonart** [comment]
Exactly the same issue here, never had this issue before, it just remains stuck on completing with a constant 0 Bytes/s. Tried re-installing, rebooting, removing the files and adding them again, re configuring my syncs, but the issue still happens.

![image](https://github.com/user-attachments/assets/3ca191c2-b6a4-45c2-8238-03214c44e73a).

No other application is using those files.

**Comment by reinaldoaru** [comment]
Same issue here...

**Comment by EzlinRye** [comment]
I'm also experiencing this exact issue. Every file that's modified gets added to the list of "Completing...". File size does not seem to have anything to do with this. Some are very small files, less than 1 MB. Others are larger.

**Comment by xWTF** [comment]
This appears to be a temporary server-side issue, starting from Dec 24 and have now been resolved. I've checked some of my MEGAcmd setups that was untouched for a while, the log suggested similar upload issues, and those setups are back to normal operation yesterday.

Although I'd still like to see some kind of official confirmation about the problem have been resolved. Maybe they should create a service status page so we know what's going on and whether it's our local setup broken or just the service being unstable for a while.

**Comment by ortmann** [comment]
On 24 November, a small number of users who were sync-updating files at an unprecedented frequency were blocked at the API level while we were trying to identify the associated bug in the sync logic that went live with version 5.6.0. Feedback collected from some of these users (thank you!) indicated that all of them actually do have frequently changing files, and the block was lifted after implementing server-side optimisations to cope with the elevated write load.

**Comment by Tetriser** [comment]
Seems like the problem is back, got this same issue months later (5.10.1)
![Image](https://github.com/user-attachments/assets/82ec14e2-a2e4-47b1-a9a1-0ef72f79110f)

**Comment by migero** [comment]
Got the same thing on 1 file in 5.10.1 will try moving it away wait for sync and replace .......
