### ISSUE TITLE
[Issue]: "Upload to MEGA" context menu entry missing

### ISSUE THREAD

**Issue by suLac4ever** [meganz/MEGAsync#1072]
# Issue

The newer versions of the MEGA installer fail to create the context menu entry "Upload to MEGA".

---

### **Steps to Reproduce (For Bug Reports)**
List the steps to reproduce the issue:

1. Download and Start the latest Mega Sync Desktop App for Windows (5.11.1.0) Setup,
2. Click through the setup leaving everything default (except "install for everyone" instead of "just for me"),
3. Let the setup complete and launch the app,
4. Attempt to upload file to MEGA by right clicking -> "Upload to MEGA" is missing from context menu.
---

### **What happened?**

"Upload to MEGA" context menu entry is missing.

---

### **What did you expect to happen?**
"Upload to MEGA" context menu entry being present like it was with older installers (eg.: 4.9.5)

---

### **Environment Details**
Provide details about the environment where the issue occurred.

- **OS**: Windows 10
- **MEGASync Version**: 5.11.1.0

**Comment by rl-mega** [comment]
Hi @suLac4ever, thanks for your report.
We could not reproduce your issue, so we'll try to troubleshoot what's happening to you.
Could you try the following:
- make sure MEGAsync is running
- kill explorer.exe from the task manager
- re-start explorer.exe
- check the context menu to see if the issue persists
- if the issue persists, we'll check whether the dll providing the Mega entries in the context menu is loaded or not. To do that:
- open a powershell prompt
- execute: `(Get-Process explorer).Modules.Where{$_.ModuleName -like "ShellExtX*"}`
- the output should be (the path of the dll might be different if you installed the app for your user only):
```
PS C:\Users\mega> (Get-Process explorer).Modules.Where{$_.ModuleName -like "ShellExtX*"}

   Size(K) ModuleName                                         FileName
   ------- ----------                                         --------
      1020 ShellExtX64.dll                                    C:\ProgramData\MEGAsync\ShellExtX64.dll
```
- if the output is empty, then the dll is not loaded and we can further investigate.

Thanks in advance and have a good day!

**Comment by tho-mas117** [comment]
> Hi [@suLac4ever](https://github.com/suLac4ever), thanks for your report. We could not reproduce your issue, so we'll try to troubleshoot what's happening to you. Could you try the following:
> 
> * make sure MEGAsync is running
> * kill explorer.exe from the task manager
> * re-start explorer.exe
> * check the context menu to see if the issue persists
> * if the issue persists, we'll check whether the dll providing the Mega entries in the context menu is loaded or not. To do that:
> * open a powershell prompt
> * execute: `(Get-Process explorer).Modules.Where{$_.ModuleName -like "ShellExtX*"}`
> * the output should be (the path of the dll might be different if you installed the app for your user only):
> 
> ```
> PS C:\Users\mega> (Get-Process explorer).Modules.Where{$_.ModuleName -like "ShellExtX*"}
> 
>    Size(K) ModuleName                                         FileName
>    ------- ----------                                         --------
>       1020 ShellExtX64.dll                                    C:\ProgramData\MEGAsync\ShellExtX64.dll
> ```
> 
> * if the output is empty, then the dll is not loaded and we can further investigate.
> 
> Thanks in advance and have a good day!

I ran the command and got ShellExtX64.dll loaded (C:\Users\[MY_USERNAME]\AppData\Local\MEGAsync\ShellExtX64.dll), but still no "Upload to MEGA" in the CLASSIC context menu (Windows 11). Can you check further?

**Comment by iSupremacy** [comment]
Same, probably 24H2 fault ill go out on a limb and assume

**Comment by suLac4ever** [comment]
I got it on Windows 10 22H2, so 24H2 can't be the explanation. Unfortunately, because of my own tries to mitigate this issue, by first installing older versions of MegaSync and the updating to latest I couldn't reproduce the initial issue I got since ... even after completely uninstalling first.

I probably would have to reinstall Windows fresh on the same machine.

If I do this anytime in the future I will report back, if the issue occurs again, but for now I can't reproduce it, to give you the shell read out you asked for.

**Comment by tho-mas117** [comment]
> I got it on Windows 10 22H2, so 24H2 can't be the explanation. Unfortunately, because of my own tries to mitigate this issue, by first installing older versions of MegaSync and the updating to latest I also could reproduce the initial issue I got since ... even after completely uninstalling first.
> 
> I probably would have to reinstall Windows fresh on the same machine.
> 
> If I do this anytime in the future I will report back, if the issue occurs again, but for now I can't reproduce it, to give you the shell read out you asked for.

Reinstalling Windows doesn't work since I have already tried it on a fresh installation on a virtual machine.

**Comment by ENunn** [comment]
having the same problem! is there any fix for this?

**Comment by rl-mega** [comment]
Hi @suLac4ever, @ENunn, @iSupremacy , @ThomasTaihei , could you try with the [latest (v5.14.0)](https://mega.io/desktop#download) version (it's only available on our website for now)? It includes a fix for the context menu issue. If it does not work, please report.
Thanks in advance and have a good day.

**Comment by tho-mas117** [comment]
> Hi [@suLac4ever](https://github.com/suLac4ever), [@ENunn](https://github.com/ENunn), [@iSupremacy](https://github.com/iSupremacy) , [@ThomasTaihei](https://github.com/ThomasTaihei) , could you try with the [latest (v5.14.0)](https://mega.io/desktop#download) version (it's only available on our website for now)? It includes a fix for the context menu issue. If it does not work, please report. Thanks in advance and have a good day.

Thank you for noticing this issue. After installing v5.14.0 and take a restart. The issue is still there, no MEGA on the classic Windows menu.

**Comment by iSupremacy** [comment]
I complete uninstalled, restarted PC then installed 5.14 from the site, still no context menu option. But there was that broken Mega button in the navigation pane by the drives (with context option ON) and you seem to have fixed that at least

**Comment by rl-mega** [comment]
Thanks for the feedback. @ThomasTaihei @iSupremacy could you try reinstalling megasync on top of the existing install (i.e. without uninstalling first), and check if the menu works? (also, please make sure the app is running when trying to check the menu, as it is never displayed when the app is not running).
Thanks again, and have a good day

**Comment by rl-mega** [comment]
(@iSupremacy good to read that the broken Mega button is repaired, thanks for reporting :) )

**Comment by tho-mas117** [comment]
> Thanks for the feedback. [@ThomasTaihei](https://github.com/ThomasTaihei) [@iSupremacy](https://github.com/iSupremacy) could you try reinstalling megasync on top of the existing install (i.e. without uninstalling first), and check if the menu works? (also, please make sure the app is running when trying to check the menu, as it is never displayed when the app is not running). Thanks again, and have a good day

I reinstalled v5.14 on top of the existing installation. Several restarts since that time, the app has always been running in the background. Still no "Upload to MEGA" on the Windows classic context menu.

**Comment by rl-mega** [comment]
@ThomasTaihei Thanks again for the feedback. Just to make sure: the "Upload to MEGA" menu entry appears in the "modern" Windows menu, but not in the "classic" one, right? How do you invoke this menu? With "shift + right click", or did you set the right value in the Windows register? Or do you use a third party app?
Thanks in advance.

**Comment by tho-mas117** [comment]
> [@ThomasTaihei](https://github.com/ThomasTaihei) Thanks again for the feedback. Just to make sure: the "Upload to MEGA" menu entry appears in the "modern" Windows menu, but not in the "classic" one, right? How do you invoke this menu? With "shift + right click", or did you set the right value in the Windows register? Or do you use a third party app? Thanks in advance.

I edited Windows registry to enable the classic menu. But even when I restored the default Win11 context menu, then choose "Show more options" or Shift + Right click, the MEGA menu is not there. It seems the MEGA menu only shows in the Win11 context menu currently.

**Comment by inverlock** [comment]
I'm having this same issue, with the same registry setting to enable the classic right click menu. It may be that when adding support for the new right click menu, they removed it from the old one as well? Just a guess

**Comment by rl-mega** [comment]
@inverlock We didn't remove support for the old menu, it should still be here.
@ThomasTaihei It is very strange that the new menu appears and not the old one. If anything, it should be the other way 'round.

Next release will have more fixes for issues identified in the installer script. Let's see if it improve things.

**Comment by rl-mega** [comment]
@inverlock, @ThomasTaihei Could you paste the output of the command (in powershell):
```Get-AppxPackage -Name "Mega*"``` ?
Thanks in advance.

**Comment by ENunn** [comment]
> [@inverlock](https://github.com/inverlock), [@ThomasTaihei](https://github.com/ThomasTaihei) Could you paste the output of the command (in powershell): `Get-AppxPackage -Name "Mega*"` ? Thanks in advance.

> Name              : MEGASyncShellSparse
> Publisher         : CN=Mega Limited, OU=IT, O=Mega Limited, STREET="Level 21, Huawei Centre, 120 Albert Street,
>                     Auckland Central", L=Auckland, S=Auckland, C=NZ, OID.1.3.6.1.4.1.311.60.2.1.3=NZ,
>                     SERIALNUMBER=9429048146128, OID.2.5.4.15=Private Organization
> Architecture      : Neutral
> ResourceId        :
> Version           : 5.14.0.3
> PackageFullName   : MEGASyncShellSparse_5.14.0.3_neutral__ejhhwke9vvc26
> InstallLocation   : C:\Program Files\WindowsApps\MEGASyncShellSparse_5.14.0.3_neutral__ejhhwke9vvc26
> IsFramework       : False
> PackageFamilyName : MEGASyncShellSparse_ejhhwke9vvc26
> PublisherId       : ejhhwke9vvc26
> IsResourcePackage : False
> IsBundle          : False
> IsDevelopmentMode : False
> NonRemovable      : False
> IsPartiallyStaged : False
> SignatureKind     : Developer
> Status            : Ok

**Comment by tho-mas117** [comment]
> [@inverlock](https://github.com/inverlock), [@ThomasTaihei](https://github.com/ThomasTaihei) Could you paste the output of the command (in powershell): `Get-AppxPackage -Name "Mega*"` ? Thanks in advance.

Name              : MEGASyncShellSparse
Publisher         : CN=Mega Limited, OU=IT, O=Mega Limited, STREET="Level 21, Huawei Centre, 120 Albert Street,
                    Auckland Central", L=Auckland, S=Auckland, C=NZ, OID.1.3.6.1.4.1.311.60.2.1.3=NZ,
                    SERIALNUMBER=9429048146128, OID.2.5.4.15=Private Organization
Architecture      : Neutral
ResourceId        :
Version           : 5.14.0.2
PackageFullName   : MEGASyncShellSparse_5.14.0.2_neutral__ejhhwke9vvc26
InstallLocation   : C:\Program Files\WindowsApps\MEGASyncShellSparse_5.14.0.2_neutral__ejhhwke9vvc26
IsFramework       : False
PackageFamilyName : MEGASyncShellSparse_ejhhwke9vvc26
PublisherId       : ejhhwke9vvc26
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
IsPartiallyStaged : False
SignatureKind     : Developer
Status            : Ok

**Comment by rl-mega** [comment]
@ENunn @ThomasTaihei You both seem to have valid version installed. Very weird. Could you please send a screenshot of the modern menu vs. classic menu? Like this:
Classic:
<img width="676" height="309" alt="Image" src="https://github.com/user-attachments/assets/3c15f779-c06b-49d8-937c-4152e0a13dba" />
Modern:

<img width="679" height="627" alt="Image" src="https://github.com/user-attachments/assets/23665c2a-53ee-475f-9021-1748d195b731" />

Thanks in advance

**Comment by tho-mas117** [comment]
<img width="337" height="328" alt="Image" src="https://github.com/user-attachments/assets/ac3d5b0e-9a51-4504-bbcd-9348f865e463" />
<img width="508" height="456" alt="Image" src="https://github.com/user-attachments/assets/d2e5b7ca-bfb3-4e75-8cd2-2339c1ba138b" />

**Comment by rl-mega** [comment]
Thanks @ThomasTaihei. Do you have any other software that could interfere with the classic menu?
Also, could you try the latest update? We've just published v5.15.0 [on our website](https://mega.io/desktop#download).

**Comment by tho-mas117** [comment]
> Thanks [@ThomasTaihei](https://github.com/ThomasTaihei). Do you have any other software that could interfere with the classic menu? Also, could you try the latest update? We've just published v5.15.0 [on our website](https://mega.io/desktop#download).

I have updated to 5.15, nothing has been fixed. And no, I don't have any other software that's messing with the classic menu. Like I said before, I have also tried to install MEGA on a fresh new virtual Windows, still got the problem.

**Comment by rl-mega** [comment]
Thanks @ThomasTaihei. The "install MEGA on a fresh new virtual Windows" scenario should be fixed though. Could you re-try it?

**Comment by tho-mas117** [comment]
> Thanks [@ThomasTaihei](https://github.com/ThomasTaihei). The "install MEGA on a fresh new virtual Windows" scenario should be fixed though. Could you re-try it?

I tried and of course, nothing has changed because the issue does not lie with Windows.
I am also a technician, and I understand that sometimes it can be very difficult to pinpoint a certain problem. I’m not asking you to fix this issue right away. I just want to speak up so that the MEGA team is aware that this problem exists and many people are experiencing it.

**Comment by rl-mega** [comment]
Thanks @ThomasTaihei. Could you tell me more about your VM setup? I'd like to replicate it to reproduce the issue (host OS, arch, guest arch, virtualization software with version...).
Thanks in advance!

**Comment by TVLover10** [comment]
I also have this issue, and it disappeared after a Windows update and no matter how many times I uninstalled and reinstall MEGA as well as restarting PC and restarting explorer, it still doesn't appear in the context menu. DLL is also loaded as per checking with the instruction found here.

**Comment by w-ponds** [comment]
I have the same issue in my Windows 11. Was working and now isn't. Tried everything mentioned above and even additional steps of uninstalling and reinstalling. Can't get the context menu items back. I suspect a windows update broke it. My system installed 25H2 on 10/8/2025 and then proceeded to install the updates shown in the following screenshot:

<img width="863" height="477" alt="Image" src="https://github.com/user-attachments/assets/1517b990-cfb4-4cc7-9413-8950839e23ca" />

I could not swear to when the break occurred but I believe it was either on 10/12/2025 or 10/15/2025. I just know it wasn't working most of last week but I didn't start troubleshooting it until this past weekend. Hopefully this will help get to the bottom of what's going on. By the way I am running MEGASync 5.16.0 64-bit.

**Comment by GSTDiandre** [comment]
Running 25H2 as well, nothing I do makes the menu appear. I don't have the modern menu, only classic.

The shell extension DLL is loaded, I've triple checked.

**Comment by w-ponds** [comment]
I'm still having the same problem myself and have not been able to solve it yet.

**Comment by davepain** [comment]
The strangest part about this is that I use the 3rd party File Explorer directory opus and for some reason the mega context menu item is present in directory Opus... It also looks different than what it used to look like, Now it has a pop out menu with only one option: " Upload to Mega"


<img width="187" height="582" alt="Image" src="https://github.com/user-attachments/assets/00cf8825-f9c3-4a31-b37f-f40aad739f73" />

**Comment by tho-mas117** [comment]
What I don't understand is MEGA unable to fix this issue, even after a long time. It's like no one on their programming team has encountered the bug that almost every user has.

**Comment by w-ponds** [comment]
That's interesting. I also use a third-party file explorer called XYplorer. It used to work great in Windows 10 with all of the Mega context menus. Hasn't worked in Windows 11 yet though. I have uninstalled XYplorer, reinstalled with admin privileges, run with admin privileges and tried other things and still can't get it to work. Also doesn't work in the native Windows File Explorer.
