### ISSUE TITLE
What is happening with Linux releases?

### ISSUE THREAD

**Issue by Perkolator** [meganz/MEGAsync#695]
The 4.6.3.0 Linux release took 27 days to appear in the mega ubuntu repo after it was listed here in the releases.

On 2 March the 4.6.5.0 version for Windows and OSX was released. And the Linux release (4.6.5-3.1) was offered in the mega ubuntu repo as an update on 10 March, while still here on github that linux release is missing.

Today, a new 4.6.5-**5**.1 version is offered in the mega ubuntu repo. **What is this version?!**

The people responsible of this repo/releases need to step up their game. It's a mess ALL the time.

**Comment by polmr** [comment]
Hi @Perkolator 
We have just pushed the tagged 4.6.5 release (https://github.com/meganz/MEGAsync/releases).
As regards to the update from the build ID 3.1 to 5.1 it's the same codebase with some adjustments in postinstallation configuration.
Note that you can always access the exact code used for building each package browsing MEGA repository: https://mega.nz/linux/repo 

Thanks for your collaboration

**Comment by Perkolator** [comment]
> We have just pushed the tagged 4.6.5 release

What do you mean by "pushed"? The `4.6.5-3.1` version was available in the mega ubuntu repo on 10 March. Why was the `4.6.5` linux release/changelog posted in github on 30 March (interestingly the next day after I started this issue), after 20 days the release was actually available to update?

> As regards to the update from the build ID 3.1 to 5.1 it's the same codebase with some adjustments in postinstallation configuration.

Why isn't this release in github releases/changelog?

> Note that you can always access the exact code used for building each package browsing MEGA repository: https://mega.nz/linux/repo

So your logic of not managing this repo properly is that users could check the code themselves, or dig up the changelogs in your above link by themselves? Well, let's see, looking at the https://mega.nz/linux/repo/xUbuntu_20.04/amd64/megasync_4.6.5-5.1_amd64.changelog I can immediately see that the `4.6.5-3.1` version isn't listed in the changelog at all. Also, the changelog has `4.6.5-5.1` as the latest update, the next is a `4.3.1` from March 2020, all other releases between those versions are missing in that changelog! What a mess..

What's the point of this github repo and the releases when you don't publish the releases/changelog properly?

Your recent `4.6.6.0` changelogs for Win and OSX, 9 days ago, mention "Fixed detected crashes on Windows, **Linux** and macOS", so where's the linux release (once again)?

**Comment by Perkolator** [comment]
4.6.8.0 for WIN and OSX was released on Jul 13, 2022. Now, 5 weeks later (35 days), the linux 4.6.8.0 version is finally offered on Mega Ubuntu 20.04 repo. But this github Mega repo releases page still doesn't have the linux version listed. The WIN and OSX release changelogs are identical, and also include a "Fixed detected crashes on Windows, Linux and macOS". You really have a weird way of releasing software updates.

**Comment by polmr** [comment]
Dear @Perkolator ,
4.7.0 for Linux is currently being thoroughly tested to ensure its quality. It will be released in time.
In the meantime, source code is available here with instructions so that anyone can build it.
Thank for your patience.

**Comment by Perkolator** [comment]
That's not what I wrote about. This underlines your fumbling around.

**Comment by polmr** [comment]
https://github.com/meganz/MEGAsync/releases/tag/v4.6.8.0_Linux

**Comment by Perkolator** [comment]
4.9.1.0_Win & 4.9.1.0_OSX have been out for over a week now, no linux version again listed in releases, nor available through ubuntu repo.

The 4.9.1.0 changelog:

> - Security upgraded.
> - Detected crashes on Windows, Linux, and macOS fixed.

Same as in the 4.9.0.0 and 4.8.9.0 and 4.8.8.0 releases. What's the point anymore with the changelogs?

So what was updated? And does the 4.9.1.0 really have a security upgrade? If it has, why isn't there a linux version out there yet?

Why can't you make these releases better?

And making better changelogs? I recently noticed that a bug with the "avg speed" in transfer manager was fixed but there's no mention about it in the changelogs at all.

**Comment by polmr** [comment]
Linux release is scheduled for next Monday. 

Changelog is a high level summary of changes conducted in between releases. We will try to make them more verbose and understandable in the future.
Btw, you can always refer to the commits in between version for a more complete list of changes.

Thanks for your understanding.
