### ISSUE TITLE
MEGAsync is changing the timestamp on desktop.ini files for no reason at every startup

### ISSUE THREAD

**Issue by Eldaw** [meganz/MEGAsync#777]
As of a recent version of the Windows MEGAsync client (I believe since v4.8.5), MEGAsync is touching the timestamp on the desktop.ini file which resides in each sync folder. Not changing the contents at all, just changing the timestamp to the current time. I've got other software monitoring/syncing some of the same folders on my system as well, and this causes mismatches to be identified (due to the changing timestamps on the desktop.ini files). There's no reason why MEGAsync should be updating these timestamps every time MEGAsync is started. And it never used to be this way. Please make it stop.

**Comment by mattw-mega** [comment]
Hi @Eldaw , It won't be MEGAsync doing that.  Actually MEGAsync ignores those files entirely due to their attributes: system+hidden.    And the only way it could touch them would be to try to download a file of the same name into that folder, if somehow a desktop.ini ended up in the MEGA folders.    It's probably Explorer itself updating those files.  thanks

**Comment by mattw-mega** [comment]
Hi @Eldaw , thanks for following up.  I have been keeping an eye on this in my own system to double check, and I did see the modification date change.   It's not the sync logic updating it, it's basically the GUI layer ensuring that sync folders have an icon shown, not by directly editing that file but by making a SHGetSetFolderCustomSettings() call for each sync on startup.    We only need to do that when a sync is first set up though, and we have an internal ticket already for a highly related issue, which is also due to executing platform related setup steps for all syncs on startup rather than just on creation.   I'll add this to that ticket and it should be addressed in the near future.   thanks

**Comment by castigo86** [comment]
Sorry to revive this post, but the issue is still present in 4.8.8. 

It reverts my custom icon to the built-in icon every time: definitely not a major issue, but it is related to the original post.

**Comment by castigo86** [comment]
The issue is unfortunately still present in 4.9.1.
